### ISSUE TITLE
sed: can't read /opt/nifi/nifi-current/conf/nifi.properties: No such file or directory

### ISSUE THREAD

**Issue by samer1977** [asdaraujo/nifi-stuff#2]
Hi asdaraugo,

I'm trying to follow your docker compose yml but i have been having an issue with persisting the nifi content into the mapped volumes! I keep getting this error:

`apache_nifi_2M4-1  | sed: can't read /opt/nifi/nifi-current/conf/nifi.properties: No such file or directory`

Not sure why it cant find it but Im guessing its looking to the host location and not finding but I thought this mapping is done to copy that info to the host if its not there . What am I missing here?

Here is how I do the mapping: 

```
services:

    apache_nifi_2M4:
        image: apache/nifi:2.0.0-M4
       
        network_mode: host
        environment:
            AUTH: ldap
            NIFI_WEB_HTTPS_PORT: 8443
            NIFI_WEB_HTTPS_HOST: ...
            KEYSTORE_PATH: "/opt/certs/keystore.p12"
            KEYSTORE_TYPE: "PKCS12"
            KEYSTORE_PASSWORD: "..."
            TRUSTSTORE_PATH: "/opt/certs/truststore.p12" 
            TRUSTSTORE_PASSWORD: "..."
            TRUSTSTORE_TYPE: "PKCS12"
            INITIAL_ADMIN_IDENTITY: "..."
            LDAP_AUTHENTICATION_STRATEGY: "SIMPLE"
            LDAP_MANAGER_DN: ".."
            LDAP_MANAGER_PASSWORD: "..."
            LDAP_USER_SEARCH_BASE: "..."
            LDAP_USER_SEARCH_FILTER: "sAMAccountName={0}"
            LDAP_IDENTITY_STRATEGY: "USE_USERNAME"
            LDAP_URL: "..." 

        
        volumes:
            - ./cert:/opt/certs
            - ./nifi-current/conf:/opt/nifi/nifi-current/conf
            - ./nifi-current/extensions:/opt/nifi/nifi-current/extensions
            - ./nifi-current/database_repository:/opt/nifi/nifi-current/database_repository
            - ./nifi-current/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - ./nifi-current/content_repository:/opt/nifi/nifi-current/content_repository
            - ./nifi-current/provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - ./nifi-current/state:/opt/nifi/nifi-current/state
            - ./nifi-current/logs:/opt/nifi/nifi-current/logs

```
Thanks for the help
